#!/usr/bin/env bash
# Builds and deploys (or upgrades) the Everything ETF program on devnet.
#
# Usage:
#   scripts/deploy-devnet.sh [--deployer <keypair.json>] [--skip-build] [--yes]
#                            [--url <rpc-url>] [--allow-new-program-id]
#
#   --deployer <path>        Wallet that pays for and owns the deploy.
#                             Default: ~/.config/solana/id.json
#   --skip-build              Don't run cargo-build-sbf; deploy the .so
#                             already at target/deploy/everything_etf.so.
#   --yes                    Don't ask for confirmation before deploying.
#   --url <rpc-url>          Override the cluster (default: devnet).
#   --allow-new-program-id   See "Program ID" below. Off by default.
#
# Program ID
# ----------
# This program's on-chain address is pinned in two places that must agree:
# `declare_id!(...)` in programs/everything-etf/src/lib.rs, and
# `[programs.devnet]` in Anchor.toml. Deploying means handing `solana
# program deploy` the *keypair* for that exact address, at
# target/deploy/everything_etf-keypair.json — and that keypair is never
# committed to git (correctly: it's gitignored, like all of target/, since
# it's a private key). So on a fresh clone/machine, cargo-build-sbf will
# happily generate a *brand new* keypair the first time it runs, and its
# pubkey will NOT match the address already baked into the source.
#
# This script refuses to deploy on that mismatch. To proceed you either:
#   1. Put the real keypair at target/deploy/everything_etf-keypair.json
#      (recover it from wherever it's kept) and re-run, or
#   2. Deliberately launch under a new address: re-run with
#      --allow-new-program-id, which patches declare_id!/Anchor.toml to the
#      freshly generated key before deploying. Only do this for a genuinely
#      new deployment — it orphans the old address for good.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

DEPLOYER="${HOME}/.config/solana/id.json"
SKIP_BUILD=0
ASSUME_YES=0
URL="devnet"
ALLOW_NEW_PROGRAM_ID=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --deployer) DEPLOYER="$2"; shift 2 ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    --yes) ASSUME_YES=1; shift ;;
    --url) URL="$2"; shift 2 ;;
    --allow-new-program-id) ALLOW_NEW_PROGRAM_ID=1; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done

log() { echo "==> $*"; }
die() { echo "error: $*" >&2; exit 1; }

PROGRAM_SO="target/deploy/everything_etf.so"
PROGRAM_KEYPAIR="target/deploy/everything_etf-keypair.json"
LIB_RS="programs/everything-etf/src/lib.rs"
ANCHOR_TOML="Anchor.toml"

# -- find the solana CLI --------------------------------------------------
# A plain `solana --version` is enough if it's already on PATH; otherwise
# fall back to the usual agave-install location.
if command -v solana >/dev/null 2>&1; then
  SOLANA_BIN_DIR="$(dirname "$(command -v solana)")"
else
  CANDIDATE="${HOME}/.local/share/solana/install/active_release/bin"
  if [[ -x "${CANDIDATE}/solana" ]]; then
    SOLANA_BIN_DIR="${CANDIDATE}"
  else
    die "solana CLI not found on PATH and not at ${CANDIDATE}. Install it (https://docs.anza.xyz/cli/install) and re-run."
  fi
fi
export PATH="${SOLANA_BIN_DIR}:${PATH}"
log "using solana CLI: $(command -v solana) ($(solana --version))"

[[ -f "${DEPLOYER}" ]] || die "deployer keypair not found at ${DEPLOYER} (pass --deployer <path>, or 'solana-keygen new -o ${DEPLOYER}' to create one)"

# -- build -------------------------------------------------------------
if [[ "${SKIP_BUILD}" -eq 0 ]]; then
  command -v cargo-build-sbf >/dev/null 2>&1 || die "cargo-build-sbf not found on PATH (it ships with the solana CLI install)"
  log "building (cargo-build-sbf)..."
  cargo-build-sbf --manifest-path programs/everything-etf/Cargo.toml --arch v1
else
  log "--skip-build: using the existing build at ${PROGRAM_SO}"
fi
[[ -f "${PROGRAM_SO}" ]] || die "${PROGRAM_SO} not found. Run without --skip-build first."

# -- program id sanity check --------------------------------------------
[[ -f "${PROGRAM_KEYPAIR}" ]] || die "${PROGRAM_KEYPAIR} not found (should have been generated by the build)"

DECLARED_ID="$(grep -oE 'declare_id!\("[^"]+"\)' "${LIB_RS}" | grep -oE '"[^"]+"' | tr -d '"')"
[[ -n "${DECLARED_ID}" ]] || die "could not parse declare_id! out of ${LIB_RS}"
KEYPAIR_ID="$(solana-keygen pubkey "${PROGRAM_KEYPAIR}")"

if [[ "${DECLARED_ID}" != "${KEYPAIR_ID}" ]]; then
  if [[ "${ALLOW_NEW_PROGRAM_ID}" -eq 0 ]]; then
    cat >&2 <<EOF
error: program ID mismatch.

  declare_id! in ${LIB_RS} says:  ${DECLARED_ID}
  ${PROGRAM_KEYPAIR} is actually: ${KEYPAIR_ID}

This almost always means the real deploy keypair for ${DECLARED_ID} is not
on this machine, and cargo-build-sbf generated a fresh, different one. See
the "Program ID" section at the top of this script for the two ways to fix
this. Refusing to deploy to avoid silently launching under the wrong address.
EOF
    exit 1
  fi

  log "WARNING: --allow-new-program-id set. Patching declare_id! and Anchor.toml to ${KEYPAIR_ID}."
  sed -i "s/${DECLARED_ID}/${KEYPAIR_ID}/" "${LIB_RS}" "${ANCHOR_TOML}"
  DECLARED_ID="${KEYPAIR_ID}"
  log "rebuilding with the new program ID baked in..."
  cargo-build-sbf --manifest-path programs/everything-etf/Cargo.toml --arch v1
fi

log "program ID: ${DECLARED_ID}"

# -- configure cluster + check / top up balance -------------------------
RPC_URL="${URL}"
case "${URL}" in
  devnet|mainnet-beta|testnet|localhost) RPC_URL="${URL}" ;; # solana CLI accepts the short names directly
esac

log "cluster: ${RPC_URL}"
DEPLOYER_PUBKEY="$(solana-keygen pubkey "${DEPLOYER}")"
log "deployer: ${DEPLOYER_PUBKEY}"

BALANCE_LAMPORTS="$(solana balance --url "${RPC_URL}" --keypair "${DEPLOYER}" --lamports 2>/dev/null | grep -oE '^[0-9]+' || echo 0)"
MIN_LAMPORTS=3000000000 # 3 SOL; a 10-asset program binary needs a few SOL in rent
if [[ "${BALANCE_LAMPORTS}" -lt "${MIN_LAMPORTS}" ]] && [[ "${RPC_URL}" == "devnet" ]]; then
  log "balance low ($((BALANCE_LAMPORTS / 1000000000)) SOL); requesting a devnet airdrop..."
  for attempt in 1 2 3; do
    if solana airdrop 2 --url "${RPC_URL}" --keypair "${DEPLOYER}"; then
      break
    fi
    log "airdrop attempt ${attempt} failed (devnet faucet is often rate-limited); retrying..."
    sleep 5
  done
fi

# -- confirm -------------------------------------------------------------
if [[ "${ASSUME_YES}" -eq 0 ]]; then
  read -r -p "Deploy ${PROGRAM_SO} to ${DECLARED_ID} on ${RPC_URL}, paid by ${DEPLOYER_PUBKEY}? [y/N] " REPLY
  [[ "${REPLY}" =~ ^[Yy]$ ]] || { log "aborted."; exit 1; }
fi

# -- deploy ----------------------------------------------------------------
log "deploying..."
solana program deploy "${PROGRAM_SO}" \
  --program-id "${PROGRAM_KEYPAIR}" \
  --keypair "${DEPLOYER}" \
  --url "${RPC_URL}"

log "deployed. verifying on-chain state:"
solana program show "${DECLARED_ID}" --keypair "${DEPLOYER}" --url "${RPC_URL}"

cat <<EOF

Next steps (not done by this script — they're one-time admin calls, not a
build/deploy concern):
  1. initialize_config  (sets protocol treasury, creation fee, protocol share)
  2. initialize_coin    (mints the fixed \$EETF supply, revokes mint authority)

create_basket reads the coin config, so no basket can exist before step 2.
See the "Deployment order" section of README.md.
EOF
